### ISSUE TITLE
Paper

### ISSUE THREAD

**Issue by IJBYHHHH** [CaveSpiderLZJ/PoseAugment-ECCV2024#1]
As a beginner, I couldn't find your article on Google Scholar. Could you please share it for study purposes?

**Comment by CaveSpiderLZJ** [comment]
I am sorry. Since the ECCV 2024 papers have not been officially released, I can not give a public link to the paper for now. However, if you are interested in it, please contact me in private through my email lizj23@mails.tsinghua.edu.cn. I can send a manuscript to you.
